app:
  name: BalanceService
server:
  port : 8081
spring:
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/balance_database
    username: ad
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest